apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres:17-alpine3.20
      volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
      envFrom:
        - configMapRef:
            name: postgres-config
      ports:
        - containerPort: 5432
  volumes:
    - name: postgres-volume
      hostPath:
        path: /C/Users/Gustavo/Documents/Projects/vendas-api-devops/volumes/postgres-volum-k8s
        type: DirectoryOrCreate
